
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.dialogItem
{
public partial class TbDialogItem
{
    private readonly System.Collections.Generic.Dictionary<int, DialogItem> _dataMap;
    private readonly System.Collections.Generic.List<DialogItem> _dataList;
    
    public TbDialogItem(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DialogItem>();
        _dataList = new System.Collections.Generic.List<DialogItem>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DialogItem _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = DialogItem.DeserializeDialogItem(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DialogItem> DataMap => _dataMap;
    public System.Collections.Generic.List<DialogItem> DataList => _dataList;

    public DialogItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DialogItem Get(int key) => _dataMap[key];
    public DialogItem this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
