
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DialogItem : Luban.BeanBase
{
    public DialogItem(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["text"].IsString) { throw new SerializationException(); }  Text = _buf["text"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = _buf["type"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
    }

    public static DialogItem DeserializeDialogItem(JSONNode _buf)
    {
        return new DialogItem(_buf);
    }

    /// <summary>
    /// 对话ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 文本信息
    /// </summary>
    public readonly string Text;
    /// <summary>
    /// 展示类型
    /// </summary>
    public readonly int Type;
    public readonly string Icon;
   
    public const int __ID__ = 608101531;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "text:" + Text + ","
        + "type:" + Type + ","
        + "icon:" + Icon + ","
        + "}";
    }
}

}
