
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Login : Luban.BeanBase
{
    public Login(JSONNode _buf) 
    {
        { if(!_buf["user"].IsString) { throw new SerializationException(); }  User = _buf["user"]; }
        { if(!_buf["password"].IsString) { throw new SerializationException(); }  Password = _buf["password"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
    }

    public static Login DeserializeLogin(JSONNode _buf)
    {
        return new Login(_buf);
    }

    /// <summary>
    /// 用户名
    /// </summary>
    public readonly string User;
    /// <summary>
    /// 密码
    /// </summary>
    public readonly string Password;
    public readonly int Level;
   
    public const int __ID__ = 73596745;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "user:" + User + ","
        + "password:" + Password + ","
        + "level:" + Level + ","
        + "}";
    }
}

}
