
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.login
{
public partial class TbLogin
{
    private readonly System.Collections.Generic.Dictionary<string, Login> _dataMap;
    private readonly System.Collections.Generic.List<Login> _dataList;
    
    public TbLogin(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, Login>();
        _dataList = new System.Collections.Generic.List<Login>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Login _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Login.DeserializeLogin(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.User, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Login> DataMap => _dataMap;
    public System.Collections.Generic.List<Login> DataList => _dataList;

    public Login GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Login Get(string key) => _dataMap[key];
    public Login this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
