
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public item.TbItem TbItem {get; }
    public login.TbLogin TbLogin {get; }
    public dialog.TbDialog TbDialog {get; }
    public dialogItem.TbDialogItem TbDialogItem {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbItem = new item.TbItem(loader("item_tbitem"));
        TbLogin = new login.TbLogin(loader("login_tblogin"));
        TbDialog = new dialog.TbDialog(loader("dialog_tbdialog"));
        TbDialogItem = new dialogItem.TbDialogItem(loader("dialogitem_tbdialogitem"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbLogin.ResolveRef(this);
        TbDialog.ResolveRef(this);
        TbDialogItem.ResolveRef(this);
    }
}

}
